name: Report Mod Incompatibility
description: Create a incompatibility report to help us improve this mod
labels: [ "compatibility", "triage" ]
body:
  -   type: input
      attributes:
        label: Minecraft Version
        description: The version of Minecraft you were using when the incompatibility occurred
      validations:
        required: true
  -   type: input
      attributes:
        label: What Mods Conflicts with
        description: Incompatible mod name
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Describe the Incompatibility
        description: A clear and concise description of what happened. If applicable, add screenshots or videos to help explain your problem.
      validations:
        required: true
  -   type: input
      attributes:
        label: Crash Report or Log
        description: If applicable, please add a **link** to the crash report or log that was created when this issue occurred. You can upload the crash report to a site like Pastebin or GitHub Gist. Please **do not** paste the whole crash report in this issue.
      validations:
        required: false