@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.adonis.createshimmer.common.fluids.experience;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;
